set termguicolors
set number
set relativenumber
set colorcolumn=140
set clipboard=unnamed
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nocompatible
filetype off

call plug#begin('~/.config/nvim/plugged')

Plug 'artanikin/vim-synthwave84'
Plug 'tpope/vim-fugitive'
Plug 'preservim/nerdtree'
Plug 'github/copilot.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'preservim/nerdcommenter'

call plug#end()

filetype plugin indent on
colorscheme synthwave84 

" NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') | NERDTree | endif
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" NERDCommenter
let g:NERDCreateDefaultMappings = 1
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDAltDelims_java = 1
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDToggleCheckAllLines = 1

" Keybindings
nmap <silent> <C-n> :NERDTreeToggle<CR>
nmap <silent> <C-p> :CtrlP<CR>
nmap <leader>gs :G<CR>
nmap <leader>gd :Gdiffsplit<CR>
nmap <leader>gp :Git push<CR>

